version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: leonardoamorimrosa/nginx:prod
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - nodejs-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: leonardoamorimrosa/node:prod
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - nodejs-network

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    tty: true
    networks:
      - nodejs-network
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dump/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb

networks:
  nodejs-network:
    driver: bridge
